<?php
function paypal_menu(){
	$items = array();
	$items['paypal/ipn'] = array(
		'title' => 'Paypal Callback',
		'page callback' => 'paypal_callback',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function paypal_callback(){
	$raw_post_data = file_get_contents('php://input');
	$raw_post_array = explode('&', $raw_post_data);
	$myPost = array();
	foreach ($raw_post_array as $keyval){
		$keyval = explode ('=', $keyval);
		if (count($keyval) == 2){
			$myPost[$keyval[0]] = urldecode($keyval[1]);
		}
	}

	$req = 'cmd=_notify-validate';
	if(function_exists('get_magic_quotes_gpc')){ $get_magic_quotes_exits = true; } 
	foreach ($myPost as $key => $value){
		if($get_magic_quotes_exits == true && get_magic_quotes_gpc() == 1){ 
			$value = urlencode(stripslashes($value)); 
		}else{
			$value = urlencode($value);
		}
		$req .= "&$key=$value";
	}

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'https://www.paypal.com/cgi-bin/webscr');
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $req);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
	curl_setopt($ch, CURLOPT_HTTPHEADER, array('Host: www.paypal.com'));
	$res = curl_exec($ch);
	curl_close($ch);


	if($_POST['payment_status'] == 'Completed'){
		watchdog('paypal',serialize($_POST));
	}

	return "";
}